- name: Create cache table
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py createcachetable"

- name: Collect static
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py collectstatic --noinput"

- name: Restart uWSGI
  become: yes
  become_user: root
  command: sudo systemctl restart uwsgi
  async: 60
  poll: 5

- name: Restart PM2 app
  become: yes
  become_user: root
  command: "sudo pm2 restart {{ project_slug }}"

- name: Restart Nginx
  become: yes
  become_user: root
  command: sudo systemctl restart nginx

