# Generated by Django 5.1.6 on 2025-05-16 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostPageAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_slug", models.CharField(db_index=True, max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("appropriateness_upvotes", models.IntegerField(default=0)),
                ("appropriateness_downvotes", models.IntegerField(default=0)),
                (
                    "appropriateness_score",
                    models.IntegerField(db_index=True, default=0),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_associations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_associations",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Page Association",
                "verbose_name_plural": "Post Page Associations",
                "ordering": ["-appropriateness_score", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="PostAppropriatenessVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_appropriateness_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appropriateness_votes",
                        to="posts.postpageassociation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Appropriateness Vote",
                "verbose_name_plural": "Post Appropriateness Votes",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="posts_post_created_183a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created_at"], name="posts_post_status_9b2301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="posts_post_author__f8ea20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postpageassociation",
            index=models.Index(
                fields=["-appropriateness_score"], name="posts_postp_appropr_50f178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postpageassociation",
            index=models.Index(
                fields=["page_slug", "-appropriateness_score"],
                name="posts_postp_page_sl_e4daeb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postpageassociation",
            index=models.Index(
                fields=["page_slug", "-added_at"], name="posts_postp_page_sl_53de6f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postpageassociation",
            unique_together={("post", "page_slug")},
        ),
        migrations.AlterUniqueTogether(
            name="postappropriatenessvote",
            unique_together={("user", "association")},
        ),
    ]
