# Generated by Django 5.0.9 on 2025-06-06 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")],
                db_index=True,
                default="en",
                help_text="The language in which this post is written",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["language", "-created_at"], name="posts_post_languag_f96c16_idx"
            ),
        ),
    ]
