# Generated by Django 5.1.6 on 2025-04-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="resource_url",
            field=models.URLField(
                blank=True,
                help_text="URL to an external resource",
                null=True,
                verbose_name="Resource URL",
            ),
        ),
    ]
