# Generated by Django 5.1.6 on 2025-04-09 13:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="about_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="About text"
            ),
        ),
    ]
