# Generated by Django 5.1.6 on 2025-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_aboutpage_about_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="wiki_url",
            field=models.URLField(blank=True, null=True, verbose_name="Wikipedia URL"),
        ),
    ]
