# Generated by Django 5.1.6 on 2025-05-17 13:23

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_learningresourcespage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostsPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posts",
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "main.basepage",
            ),
        ),
    ]
