# Generated by Django 5.1.6 on 2025-05-02 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("image", "Image"),
                            ("website", "Website"),
                            ("article", "Article"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quality_vote_count", models.IntegerField(default=0)),
                ("quality_vote_sum", models.IntegerField(default=0)),
                ("accessibility_beginner_count", models.IntegerField(default=0)),
                ("accessibility_moderate_count", models.IntegerField(default=0)),
                ("accessibility_advanced_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Learning Resource",
                "verbose_name_plural": "Learning Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="learning_re_created_19546a_idx"
                    ),
                    models.Index(
                        fields=["-quality_vote_sum", "-quality_vote_count"],
                        name="learning_re_quality_5156c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourcePageAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_slug", models.CharField(db_index=True, max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("appropriateness_upvotes", models.IntegerField(default=0)),
                ("appropriateness_downvotes", models.IntegerField(default=0)),
                (
                    "appropriateness_score",
                    models.IntegerField(db_index=True, default=0),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_associations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_associations",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Page Association",
                "verbose_name_plural": "Resource Page Associations",
                "ordering": ["-appropriateness_score", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="AppropriatenessVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appropriateness_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appropriateness_votes",
                        to="learning_resources.resourcepageassociation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appropriateness Vote",
                "verbose_name_plural": "Appropriateness Votes",
            },
        ),
        migrations.CreateModel(
            name="ResourceURL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource URL",
                "verbose_name_plural": "Resource URLs",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("moderate", "Moderate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_votes",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Vote",
                "verbose_name_plural": "Accessibility Votes",
                "unique_together": {("user", "learning_resource")},
            },
        ),
        migrations.CreateModel(
            name="QualityVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "learning_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_votes",
                        to="learning_resources.learningresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Vote",
                "verbose_name_plural": "Quality Votes",
                "unique_together": {("user", "learning_resource")},
            },
        ),
        migrations.AddIndex(
            model_name="resourcepageassociation",
            index=models.Index(
                fields=["-appropriateness_score"], name="learning_re_appropr_96f31b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcepageassociation",
            index=models.Index(
                fields=["page_slug", "-appropriateness_score"],
                name="learning_re_page_sl_6fe473_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourcepageassociation",
            unique_together={("learning_resource", "page_slug")},
        ),
        migrations.AlterUniqueTogether(
            name="appropriatenessvote",
            unique_together={("user", "association")},
        ),
    ]
