# Generated by Django 5.1.6 on 2025-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="ai_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI-generated summary"
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="ai_summary_generated",
            field=models.BooleanField(
                default=False, verbose_name="AI summary has been generated"
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="ai_summary_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="When AI summary was generated"
            ),
        ),
    ]
