# Generated by Django 5.1.6 on 2025-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0003_alter_learningresource_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("youtube", "YouTube"),
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("website", "Website"),
                    ("article", "Article"),
                    ("book", "Book"),
                    ("course", "Course"),
                    ("tool", "Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
