# Generated by Django 5.1.6 on 2025-06-05 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0004_alter_learningresource_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISuggestedResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_slug", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("website", "Website"),
                            ("book", "Book"),
                            ("course", "Course"),
                            ("documentation", "Documentation"),
                            ("tutorial", "Tutorial"),
                            ("github", "GitHub Repository"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_added", models.BooleanField(default=False)),
                (
                    "learning_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestion_origin",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Suggested Resource",
                "verbose_name_plural": "AI Suggested Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["page_slug"], name="learning_re_page_sl_c97202_idx"
                    )
                ],
                "unique_together": {("page_slug", "url")},
            },
        ),
    ]
