# Generated by Django 5.0.9 on 2025-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0005_aisuggestedresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")],
                db_index=True,
                default="en",
                help_text="The language of this learning resource",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="aisuggestedresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("youtube", "YouTube"),
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("website", "Website"),
                    ("article", "Article"),
                    ("book", "Book"),
                    ("course", "Course"),
                    ("documentation", "Documentation"),
                    ("tutorial", "Tutorial"),
                    ("tool", "Tool"),
                ],
                default="website",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("youtube", "YouTube"),
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("website", "Website"),
                    ("article", "Article"),
                    ("book", "Book"),
                    ("course", "Course"),
                    ("documentation", "Documentation"),
                    ("tutorial", "Tutorial"),
                    ("tool", "Tool"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["language", "-created_at"],
                name="learning_re_languag_057664_idx",
            ),
        ),
    ]
