# Generated by Django 5.1.6 on 2025-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0005_aisuggestedresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("ru", "Russian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                ],
                db_index=True,
                default="en",
                help_text="The language of this learning resource",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["language", "-created_at"],
                name="learning_re_languag_057664_idx",
            ),
        ),
    ]
